# Generated by Django 6.0.6 on 2026-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPSServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly display name', max_length=100)),
                ('base_url', models.URLField(help_text='Base URL of the VPS Pilot instance, e.g. https://vps2.example.com')),
                ('api_token', models.CharField(help_text='METRICS_API_TOKEN configured on the remote VPS', max_length=128)),
                ('is_local', models.BooleanField(default=False, help_text='Whether this is the server running this application')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPS Server',
                'verbose_name_plural': 'VPS Servers',
                'ordering': ['-is_local', 'name'],
            },
        ),
    ]
